name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Change this to your desired branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn

    - name: Deploy with gh-pages
      run: yarn deploy
