
 

name: Yarn Build Check

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: v20.19.0  # Specify the desired Node.js version
    
    - name: Install dependencies
      run: yarn install --ignore-platform

    - name: Build 
      run: yarn build

    - name: Test
      run: yarn test
